language: ruby

services:
  - postgresql

bundler_args: "--without development --jobs=3"

cache: bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:create
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails db:seed

script:
  - bin/rails test

notifications:
  email: false